/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectopds1;

import javax.swing.JOptionPane;

/**
 *
 * @author Santiago Gómez
 */
public class PantallaBienvenida extends javax.swing.JFrame {
    
    //Variables globales
     static String[] actividadesCortoPlazo = new String[100];
    static int[] horasSemanales = new int[100];
    static String[] actividadesLargoPlazo = new String[100];
    static int[] meses = new int[100];
    static int numActividadesCortoPlazo = 0;
    static int numActividadesLargoPlazo = 0;

    /**
     * Creates new form PantallaBienvenida
     */
    public PantallaBienvenida() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jButton6.setText("AYUDA DE EMERGENCIA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO A TU APLICACIÓN DE CONFIANZA SOBRE SALUD MENTAL");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("DIARIO PERSONAL");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("RECOMPENSAS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("PROGRAMAR ACTIVIDADES");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("RECURSOS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("AUTODIAGNÓSTICO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("AYUDA DE EMERGENCIA");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    String input = JOptionPane.showInputDialog("Bienvenido a tu diario personal, este es un espacio seguro en el que puedas expresar tus pensamientos de manera privada, siéntete libre de escribir lo que desees");
    
    if (input != null && !input.isEmpty()) {
            // Muestra un mensaje adicional
            JOptionPane.showMessageDialog(null, "¡Gracias por expresar tus pensamientos en el día de hoy, recuerda que esto es una gran ayuda para tu salud mental!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // El usuario no ingresó información
            JOptionPane.showMessageDialog(null, "Aún no ingresaste ninguna información. Tu diario está en blanco.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "Bienvenido al sistema de recompensas");

        String diasStr = JOptionPane.showInputDialog("Digite la cantidad de días en que ha iniciado la aplicación:");
        int dias = Integer.parseInt(diasStr);

        if (dias >= 7 && dias < 14) {
            JOptionPane.showMessageDialog(null, "Ahora tienes acceso a una llamada con nuestro profesional de la salud Samuel, su número es: 323 4294978");
        } else if (dias >= 15 && dias < 30) {
            JOptionPane.showMessageDialog(null, "Vas por gran camino, tu recompensa esta vez es acceso gratuito a los documentos dispuestos por la OMS acerca de la salud mental");
        } else if (dias >= 30) {
            JOptionPane.showMessageDialog(null, "Tu progreso es impresionante, has alcanzado el nivel máximo.");
            JOptionPane.showMessageDialog(null, "Te otorgamos este certificado por usar nuestra aplicación:");
            String url = "https://drive.google.com/file/d/1IL2QeSQtZt5Fuyg3MLhHi1SUu8fbLDjF/view?usp=sharing";

            try {
                // Abre la página web en el navegador predeterminado
                java.awt.Desktop.getDesktop().browse(new java.net.URI(url));
            } catch (java.io.IOException | java.net.URISyntaxException e) {
                // Maneja cualquier excepción que pueda ocurrir
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Sigue intentándolo, recuerda que tu primera recompensa comienza en el día 7 de uso.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JOptionPane.showMessageDialog(null, "Bienvenido al sistema de programación de actividades. Seleccione una opción:");

        String[] opciones = {"Semanales", "A largo plazo", "Mostrar actividades"};
        int opcion = JOptionPane.showOptionDialog(null, "Seleccione una opción:", "Sistema de Programación de Actividades", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

        if (opcion == 0) { // Opción Semanales
            int n = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad de actividades semanales:"));

            for (int i = 0; i < n; i++) {
                String actividad = JOptionPane.showInputDialog("Ingrese el nombre de la actividad " + (i + 1) + ":");
                actividadesCortoPlazo[numActividadesCortoPlazo] = actividad;
                int horas = Integer.parseInt(JOptionPane.showInputDialog("Ingrese las horas semanales dedicadas a " + actividad + ":"));
                horasSemanales[numActividadesCortoPlazo] = horas;
                numActividadesCortoPlazo++;
            }
        } else if (opcion == 1) { // Opción A largo plazo
            int n = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad de actividades a largo plazo:"));

            for (int i = 0; i < n; i++) {
                String actividad = JOptionPane.showInputDialog("Ingrese el nombre de la actividad " + (i + 1) + ":");
                actividadesLargoPlazo[numActividadesLargoPlazo] = actividad;
                int mes = Integer.parseInt(JOptionPane.showInputDialog("Ingrese los meses dedicados a " + actividad + ":"));
                meses[numActividadesLargoPlazo] = mes;
                numActividadesLargoPlazo++;
            }
        }

        String actividadesSemanales = "Actividades semanales:\n";
        for (int i = 0; i < numActividadesCortoPlazo; i++) {
            actividadesSemanales += actividadesCortoPlazo[i] + ": " + horasSemanales[i] + " horas semanales\n";
        }

        String actividadesLargoPlazoStr = "Actividades a largo plazo:\n";
        for (int i = 0; i < numActividadesLargoPlazo; i++) {
            actividadesLargoPlazoStr += actividadesLargoPlazo[i] + ": " + meses[i] + " meses\n";
        }

        JOptionPane.showMessageDialog(null, actividadesSemanales);
        JOptionPane.showMessageDialog(null, actividadesLargoPlazoStr);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Recursos pantallaRecursos = new Recursos();
        pantallaRecursos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String[] preguntas = {
            "¿Poco interés o placer por hacer cosas?",
            "¿Se siente mal, deprimido o desesperanzado?",
            "¿Tiene problemas para conciliar o mantener el sueño, o duerme demasiado?",
            "¿Se siente cansado o con poca energía?",
            "¿Tiene poco apetito o come en exceso?",
            "¿Se siente mal consigo mismo, o cree que es un fracasado o que se ha defraudado a sí mismo o a su familia?",
            "¿Problemas para concentrarse en cosas, como leer el periódico o ver la televisión?",
            "¿Se mueve o habla tan despacio que los demás podrían haberlo notado? ¿O tan inquieto o inquieta que se ha movido mucho más de lo habitual?",
            "¿Tines pensamientos de que estarías mejor muerto, o pensamientos de hacerte daño de alguna manera?"
        };

        int resultado = 0;

        for (int i = 0; i < preguntas.length; i++) {
            String pregunta = preguntas[i] + "\n" +
                    "1: No en absoluto\n" +
                    "2: En varios días\n" +
                    "3: Más de la mitad de los días\n" +
                    "4: Casi todos los días";

            String[] opciones = {"No en absoluto", "En varios días", "Más de la mitad de los días", "Casi todos los días"};
            int opcion = JOptionPane.showOptionDialog(null, pregunta, "Diagnóstico de Depresión", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

            switch (opcion) {
                case 0:
                    resultado += 0;
                    break;
                case 1:
                    resultado += 1;
                    break;
                case 2:
                    resultado += 2;
                    break;
                case 3:
                    resultado += 3;
                    break;
            }
        }

        String diagnostico = "";
        if (resultado >= 0 && resultado <= 4) {
            diagnostico = "Depresión mínima o nula; Vigilar, puede no requerir tratamiento.";
        } else if (resultado >= 5 && resultado <= 9) {
            diagnostico = "Depresión leve; Utilizar el juicio clínico (duración de los síntomas, deterioro funcional) para determinar la necesidad de tratamiento.";
        } else if (resultado >= 10 && resultado <= 14) {
            diagnostico = "Depresión moderada; Utilizar el juicio clínico (duración de los síntomas, deterioro funcional) para determinar la necesidad de tratamiento.";
        } else if (resultado >= 15 && resultado <= 19) {
            diagnostico = "Depresión moderadamente grave; Garantiza un tratamiento activo con psicoterapia, medicación o una combinación de ambos.";
        } else if (resultado >= 20 && resultado <= 27) {
            diagnostico = "Depresión grave; Garantiza un tratamiento activo con psicoterapia, medicación o una combinación de ambos.";
        }

        JOptionPane.showMessageDialog(null, diagnostico);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JOptionPane.showMessageDialog(null, "Esta es nuestra línea de emergencia, para comunicarte con el profesional Santiago, llama a este número de inmediato\n" +
                                     "305 3230459", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaBienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
